### ISSUE TITLE
Bugs in Dockerfile.lambda

### ISSUE THREAD

**Issue by RoyEngelen** [binxio/cfn-oracle-user-provider#1]
Dear,

I cloned your repo and when I try to build the container I get the following error:
chmod: cannot access '/lambda/setuptools/script': No such file or directory
chmod: cannot access '(dev).tmpl': No such file or directory
chmod: cannot access '/lambda/setuptools/command/launcher': No such file or directory
chmod: cannot access 'manifest.xml': No such file or directory

Also, this step fails, because there is no libaio available.
# Add libaio
RUN cp /lib/x86_64-linux-gnu/libaio.so.1.0.1 /lambda && \
	ln -sf /lambda/libaio.so.1.0.1 /lambda/libaio.so.1

Are you still updating this repo, if not do you have any suggestions how to fix these errors?

Thanks in advance!

Roy

**Comment by mvanholsteijn** [comment]
Hi Roy, it is fixed. We are still maintaining this repo, but due to the licensing issues with Oracle it is a bit harder as for any of the other providers we have.
