### ISSUE TITLE
Zip file exceed lambda limit

### ISSUE THREAD

**Issue by RoyEngelen** [binxio/cfn-oracle-user-provider#2]
Hi Mark,

When I want to create a lambda function with the zip file that is build, then I get the error that the unzip size of the lambda function is too big. Is this problem known and do you have any advice how to solve this? 

Thanks in advance!

**Comment by mvanholsteijn** [comment]
OMG. De oracle client libraries zijn geexplodeerd! Ik heb boto3 uit de distributie gehaald., dan valt ie er weer net binnen.

**Comment by mvanholsteijn** [comment]
@RoyEngelen laat me even weten of het nu weer past..

**Comment by RoyEngelen** [comment]
Hi Mark,

Ik heb de zip opnieuw gebouwd, maar hij is nog altijd te groot.
Unzipped moet het kleiner zijn dan 262MB en dan is nu nog 510MB.

Kunnen we nog meer dingen verwijderen?

Groet,

Roy

**Comment by mvanholsteijn** [comment]
Hi Roy,

Bij mij is de inhoud van de zip, zonder boto3 33Mb en de inhoud uitgepakt 114Mb. 

Cheers,

Mark

**Comment by RoyEngelen** [comment]
Hi Mark,

Check werkt nu! Ik had de nieuwste versie van instantclient genomen, maar die is dus aanzienlijk groter. 

Bedankt voor de hulp!!

Roy
