### ISSUE TITLE
unable import module cx_oracle

### ISSUE THREAD

**Issue by RoyEngelen** [binxio/cfn-oracle-user-provider#3]
Hi Mark,

Als ik de lambda probeer te runnen dan krijg ik de fout melding dat die de module cx_oracle niet kan importeren, terwijl de dockerfile de requierements wel installeert. Enig idee waarom lambda die module niet kan vinden?

Alvast bedankt!

Roy

**Comment by mvanholsteijn** [comment]
difficult to tell, but try this:

```
cd target
unzip *.zip
docker run -v $PWD:/lambda -w /lambda -i -e LD_LIBRARY_PATH=/lambda python:3.7 <<!
import cx_Oracle
cx_Oracle.connect()
!
```
It should print out:

```
cx_Oracle.DatabaseError: ORA-12162: TNS:net service name is incorrectly specified
```

But may you will get a more telling error.

**Comment by RoyEngelen** [comment]
Thanks! Was an useful tip! The instant client was not correct installed. Everything is working now!
